### ISSUE TITLE
RTEMS zlib redefines symbols globally

### ISSUE THREAD

**Issue by eproxus** [grisp/grisp2-rtems-toolchain#12]
The zlib implementation that comes with RTEMS seems to redefine a lot of symbols globally, causing compilation problems for software that uses symbols with the same name:

```
beam/erl_db_util.h:596:21: error: 'union erl_off_heap_ptr' has no member named 'z_voidp'; did you mean 'voidp'?
     if ((UWord)ohp->voidp % sizeof(UWord) != 0) {
```

caused by this line in `external/rtems/cpukit/include/zlib.h`:
```
122: #  define voidp                 z_voidp
```

Is there a way to fix or workaround this?

**Comment by peerst** [comment]
That happens here.

And apparently this header is included either in one of the default headers or in the Erlang runtime directly.  This macro messing is not nice.  First pollute the namespace, then to "fix" it mess up all kinds of symbols with macros.

```
/* zconf.h -- configuration of the zlib compression library
 * Copyright (C) 1995-2010 Jean-loup Gailly.
 * For conditions of distribution and use, see copyright notice in zlib.h
 */

#ifndef ZCONF_H
#define ZCONF_H

/*
 * If you *really* need a unique prefix for all types and library functions,
 * compile with -DZ_PREFIX. The "standard" zlib should be compiled without it.
 * Even better than compiling with -DZ_PREFIX would be to use configure to set
 * this permanently in zconf.h using "./configure --zprefix".
 */
#if 1 /* is set to #if 1 for RTEMS */

/* all linked symbols */
#  define _dist_code            z__dist_code
#  define _length_code          z__length_code
#  define _tr_align             z__tr_align
#  define _tr_flush_block       z__tr_flush_block
#  define _tr_init              z__tr_init
#  define _tr_stored_block      z__tr_stored_block
#  define _tr_tally             z__tr_tally
#  define adler32               z_adler32
#  define adler32_combine       z_adler32_combine
#  define adler32_combine64     z_adler32_combine64
#  define compress              z_compress
#  define compress2             z_compress2
#  define compressBound         z_compressBound
#  define crc32                 z_crc32
#  define crc32_combine         z_crc32_combine
#  define crc32_combine64       z_crc32_combine64
#  define deflate               z_deflate
#  define deflateBound          z_deflateBound
#  define deflateCopy           z_deflateCopy
#  define deflateEnd            z_deflateEnd
#  define deflateInit2_         z_deflateInit2_
#  define deflateInit_          z_deflateInit_
#  define deflateParams         z_deflateParams
#  define deflatePrime          z_deflatePrime
#  define deflateReset          z_deflateReset
#  define deflateSetDictionary  z_deflateSetDictionary
#  define deflateSetHeader      z_deflateSetHeader
#  define deflateTune           z_deflateTune
#  define deflate_copyright     z_deflate_copyright
#  define get_crc_table         z_get_crc_table
#  define gz_error              z_gz_error
#  define gz_intmax             z_gz_intmax
#  define gz_strwinerror        z_gz_strwinerror
#  define gzbuffer              z_gzbuffer
#  define gzclearerr            z_gzclearerr
#  define gzclose               z_gzclose
#  define gzclose_r             z_gzclose_r
#  define gzclose_w             z_gzclose_w
#  define gzdirect              z_gzdirect
#  define gzdopen               z_gzdopen
#  define gzeof                 z_gzeof
#  define gzerror               z_gzerror
#  define gzflush               z_gzflush
#  define gzgetc                z_gzgetc
#  define gzgets                z_gzgets
#  define gzoffset              z_gzoffset
#  define gzoffset64            z_gzoffset64
#  define gzopen                z_gzopen
#  define gzopen64              z_gzopen64
#  define gzprintf              z_gzprintf
#  define gzputc                z_gzputc
#  define gzputs                z_gzputs
#  define gzread                z_gzread
#  define gzrewind              z_gzrewind
#  define gzseek                z_gzseek
#  define gzseek64              z_gzseek64
#  define gzsetparams           z_gzsetparams
#  define gztell                z_gztell
#  define gztell64              z_gztell64
#  define gzungetc              z_gzungetc
#  define gzwrite               z_gzwrite
#  define inflate               z_inflate
#  define inflateBack           z_inflateBack
#  define inflateBackEnd        z_inflateBackEnd
#  define inflateBackInit_      z_inflateBackInit_
#  define inflateCopy           z_inflateCopy
#  define inflateEnd            z_inflateEnd
#  define inflateGetHeader      z_inflateGetHeader
#  define inflateInit2_         z_inflateInit2_
#  define inflateInit_          z_inflateInit_
#  define inflateMark           z_inflateMark
#  define inflatePrime          z_inflatePrime
#  define inflateReset          z_inflateReset
#  define inflateReset2         z_inflateReset2
#  define inflateSetDictionary  z_inflateSetDictionary
#  define inflateSync           z_inflateSync
#  define inflateSyncPoint      z_inflateSyncPoint
#  define inflateUndermine      z_inflateUndermine
#  define inflate_copyright     z_inflate_copyright
#  define inflate_fast          z_inflate_fast
#  define inflate_table         z_inflate_table
#  define uncompress            z_uncompress
#  define zError                z_zError
#  define zcalloc               z_zcalloc
#  define zcfree                z_zcfree
#  define zlibCompileFlags      z_zlibCompileFlags
#  define zlibVersion           z_zlibVersion

/* all zlib typedefs in zlib.h and zconf.h */
#  define Byte                  z_Byte
#  define Bytef                 z_Bytef
#  define alloc_func            z_alloc_func
#  define charf                 z_charf
#  define free_func             z_free_func
#  define gzFile                z_gzFile
#  define gz_header             z_gz_header
#  define gz_headerp            z_gz_headerp
#  define in_func               z_in_func
#  define intf                  z_intf
#  define out_func              z_out_func
#  define uInt                  z_uInt
#  define uIntf                 z_uIntf
#  define uLong                 z_uLong
#  define uLongf                z_uLongf
#  define voidp                 z_voidp
#  define voidpc                z_voidpc
#  define voidpf                z_voidpf

/* all zlib structs in zlib.h and zconf.h */
#  define gz_header_s           z_gz_header_s
#  define internal_state        z_internal_state

#endif

```

**Comment by peerst** [comment]
Since zlib is quite used in Erlang I fear its one of these uses that is picking up the RTEMS zlib.

https://github.com/erlang/otp/search?q=zlib.h&unscoped_q=zlib.h

**Comment by c-mauderer** [comment]
>  This macro messing is not nice. First pollute the namespace, then to "fix" it mess up all kinds of symbols with macros.

I agree that this is not a really an optimal solution. But it's one offered by zlib itself. RTEMS is only using it. The original zconf.h had an `#ifdef Z_PREFIX` instead of the `#ifdef 1` in RTEMS.

RTEMS uses that since quite a long time. So I'm really surprised that it hasn't been a problem for GRiSP1. What changed?

**Comment by sebhub** [comment]
I once tried to submit a patch to zlib, but this project is extremely conservative.

**Comment by eproxus** [comment]
The only conclusion I can draw is that `Z_PREFIX` is somehow defined when running our RTEMS build. Erlang doesn't build at all with those symbols renamed. I can't figure out where and why this seems to be set though...

**Comment by eproxus** [comment]
Grepping through the toolchain and my OTP build directory I find _no_ instances of that being set...

**Comment by eproxus** [comment]
Hmm, the file at `external/rtems/cpukit/include/zconf.h` has this hardcoded set to `1` 😮

**Comment by c-mauderer** [comment]
Like I said:
> The original zconf.h had an #ifdef Z_PREFIX instead of the #ifdef 1 in RTEMS.

But that shouldn't make a difference. It had this hard coded value for the first GRiSP too. So I'm really curious why it didn't make a problem back then? What changed since then?

Like sebhub said: The defines are done in the upstream Zlib. I don't think that it would be a good idea to do something substantially different for RTEMS. Especially changing something that has been that long in RTEMS might could be a bit difficult too.

**Comment by eproxus** [comment]
@c-mauderer Ah, missed that, sorry.

Agree about not changing it upstream. Perhaps the include order is different somehow now, and Erlang picked up its own `zlib.h` before...

**Comment by c-mauderer** [comment]
Would adding the Z_PREFIX define help? Maybe Erlang adapts to it?

**Comment by eproxus** [comment]
No, I discovered that Erlang isn't tested with `Z_PREFIX` set and doesn't work at all with it. :-(

**Comment by sebhub** [comment]
It seems the trouble is cased by these defines:
```
/* all zlib typedefs in zlib.h and zconf.h */
#  define Byte                  z_Byte
#  define Bytef                 z_Bytef
#  define alloc_func            z_alloc_func
#  define charf                 z_charf
#  define free_func             z_free_func
#  define gzFile                z_gzFile
#  define gz_header             z_gz_header
#  define gz_headerp            z_gz_headerp
#  define in_func               z_in_func
#  define intf                  z_intf
#  define out_func              z_out_func
#  define uInt                  z_uInt
#  define uIntf                 z_uIntf
#  define uLong                 z_uLong
#  define uLongf                z_uLongf
#  define voidp                 z_voidp
#  define voidpc                z_voidpc
#  define voidpf                z_voidpf

/* all zlib structs in zlib.h and zconf.h */
#  define gz_header_s           z_gz_header_s
#  define internal_state        z_internal_state
```
This stuff makes no sense at all. One option is to disable this stuff with an #ifndef __rtems__.

**Comment by peerst** [comment]
Yes its these defines.  And I agree it makes no sense.

Question is also why RTEMS needs them.  

Are you suggestion to only have them on when RTEMS itself is compiled with the ifndef items?  But wouldn't we then get a zlib in RTEMS which have theses z_* names and see a header from Erlang without them and then just get a linker error because we are missing the normal lib functions?

**Comment by peerst** [comment]
Oh you mean only the typedefs!

**Comment by sebhub** [comment]
Yes, the typedefs and the structs. For the global functions the namespace makes sense.

**Comment by peerst** [comment]
That actually worked for us: https://github.com/grisp/grisp2-rtems-toolchain/commit/343ab3aec5b45a3b9cabc7db8e5ecfb491a2aab2

And https://github.com/grisp/rtems/tree/peerst/zconf-fix

Hope I didn't mess up the submodules, not very experienced with them @c-mauderer please check if everything is ok.  N.B. The change in rtems is on the peers/zconf-fix branch feel free to merge it if its ok.

**Comment by c-mauderer** [comment]
It's interesting that the patch works like that. It should be
```
#ifndef __rtems__
```
instead of
```
#ifndef rtems
```
It seems that the markdown formatting messed with @sebhub's suggestion. Can you try whether that works too?

Otherwise it should be fine (except maybe for the commit message style: For most git projects it's a 50 char subject line, one empty line and then a description wrapped at 72 chars).

We might get a merge conflict with my pending pull request #13. If the test with `__rtems__` works too, I would suggest that I put the commit on top of that pull request and merge it together.

**Comment by c-mauderer** [comment]
I've seen that you added it to master already. So I'll adapt my pull request instead.

**Comment by peerst** [comment]
Caution: I did not rebuild rtems yet, should have done before pushing something but was in a hurry ;-)  So it might well be mine doesn't work in RTEMS

**Comment by c-mauderer** [comment]
I'm still not sure about `rtems` vs `__rtems__` in the patch but that will be a problem as soon as it should be integrated upstream.

**Comment by eproxus** [comment]
@c-mauderer What do you mean?

**Comment by peerst** [comment]
I'm not sure either: I'd rather go with __rtems__

**Comment by c-mauderer** [comment]
Like said above (when reviewing @peerst patch):

> It's interesting that the patch works like that. It should be
> 
> ```
> #ifndef __rtems__
> ```
> 
> instead of
> 
> ```
> #ifndef rtems
> ```
> 
> It seems that the markdown formatting messed with @sebhub's suggestion. Can you try whether that works too?

Normally these #ifdef are done with `__rtems__`.

**Comment by eproxus** [comment]
@c-mauderer Are you saying just `rtems` doesn't exist and won't work?

**Comment by c-mauderer** [comment]
It seems to work for you so it seems to exist. I wanted to say that the usual define to check for is `__rtems__`. That one is used throughout imported code in RTEMS core repository as well as all add ons like libbsd.

**Comment by eproxus** [comment]
Got it, then we'll use `__rtems__` instead 👍

**Comment by c-mauderer** [comment]
I'll just update the PR #13 branch again in the next few minutes and you can test it with that. If everything works well: Please just merge it.

**Comment by peerst** [comment]
> It seems to work for you so it seems to exist. I wanted to say that the usual define to check for is `__rtems__`. That one is used throughout imported code in RTEMS core repository as well as all add ons like libbsd.

That might be a misconception: I hacked it in the header of the built toolchain (was doing it while live coding on Twitch so no time to rebuild the toolchain).  When building Erlang the important thing is that its *not* defined which it is also if it doesn't even exist.  But one needs to rebuild the toolchain with it and then Erlang and only then we know if it would really work.

**Comment by c-mauderer** [comment]
> > It seems to work for you so it seems to exist. I wanted to say that the usual define to check for is `__rtems__`. That one is used throughout imported code in RTEMS core repository as well as all add ons like libbsd.
> 
> That might be a misconception: I hacked it in the header of the built toolchain (was doing it while live coding on Twitch so no time to rebuild the toolchain). When building Erlang the important thing is that its _not_ defined which it is also if it doesn't even exist. But one needs to rebuild the toolchain with it and then Erlang and only then we know if it would really work.

You had an `#ifndef rtems`. So if it wouldn't have been defined, the file wouldn't have changed. But it changed something for you so it most likely is defined.

`__rtems__` is defined for sure. So `#ifndef __rtems__` removes code.

In that case you don't have to rebuild the whole tool chain but only the BSP and maybe some libs. The toolchain is only necessary if `external/rtems-source-builder` changes. I hope that only happens one time in the near future when we finalize the package. Till then I try to stay on the current version. So it should be enough to do a
```
make bsp libbsd libgrisp libinih demo-clean demo
```
which should be only a few minutes compared to the 1/2 to over 1 hour of the complete tool chain.

**Comment by c-mauderer** [comment]
I'm not sure why `rtems` worked. I did a check and it's not defined by the compiler. The compiler knows only `__rtems__`. So maybe from some header.
```
> arm-rtems5-gcc -dM -E - < /dev/null | grep -i rtems
#define __VERSION__ "7.5.0 20191114 (RTEMS 5, RSB 5 (6d194ca849ec modified), Newlib 7947581)"
#define __rtems__ 1
```
Anyway: Please check the PR #13 branch and - if it works - just click the merge button.

**Comment by eproxus** [comment]
@c-mauderer Since it is an `ifndef` it might as well have been `#ifndef foobarbaz` and it would still have worked?

**Comment by peerst** [comment]
> You had an `#ifndef rtems`. So if it wouldn't have been defined, the file wouldn't have changed. But it changed something for you so it most likely is defined.
> 
> `__rtems__` is defined for sure. So `#ifndef __rtems__` removes code.

I'm confused now:  is `__rtems__` only defined for building RTEMS itself or also when building our stuff?

**Comment by peerst** [comment]
> @c-mauderer Since it is an `ifndef` it might as well have been `#ifndef foobarbaz` and it would still have worked?

But then the #defines that disturb building Erlang would have been in and it would be as if we hadn't changed anything which didn't work

**Comment by c-mauderer** [comment]
@eproxus and @peerst: `foobarbaz` is _not_ defined. So that code would throw an error:
```
#ifndef foobarbaz
#error foobarbaz is not defined
#endif
```
The same is true for the types in the header. It was encapsulated with an `#infndef rtems` so if `rtems` wouldn't be defined somewhere the defines would still be there. Therefore I assume it had been defined somewhere. But it's not an official feature as far as I know and most likely only worked by chance.

@peerst: `__rtems__` is allways defined if you use the arm-rtems5-gcc with default options. It's just like a `__linux__` define for Linux.

**Comment by peerst** [comment]
I think `rtems` is a legacy define because it looked familiar to me from ancient times.  Of course `__rtems__` is much cleaner so it probably has been added later but `rtems` stayed for backwards compatibility

**Comment by eproxus** [comment]
@peerst Is this fixed with `__rtems__` now?

**Comment by c-mauderer** [comment]
I'm preparing a bunch of patches for RTEMS upstream. I would like to include the one from this issue too (in this form):

    https://github.com/grisp/rtems/commit/8452f2dddafa57a2e400c93dd9a788e0fa597836

Is that problem solved with the patch?

Especially @peerst: You originally authored the patch. I adapted it later to match the commit message style usually used in RTEMS. Is that OK for you? If yes I would remove the following part before sending it to RTEMS:

> Christian Mauderer <christian.mauderer@embedded-brains.de>:
> I Adapted the commit message to match the usual format and changed
> ifdef rtems to ifdef __rtems__."

**Comment by eproxus** [comment]
Closing because we don't have the issue anymore.
