### ISSUE TITLE
OpenOCD integration

### ISSUE THREAD

**Issue by c-mauderer** [grisp/grisp2-rtems-toolchain#14]
I'm working on the JTAG (hardware patch and software setup). @eproxus or @peerst: For GRiSP1 we have added a OpenOCD source package and build it with the build scripts.

- I assume that we should build OpenOCD in this repository again?
- OpenOCD hasn't had a release since November 2018. I think it would be a good idea to just pick the master development branch to get the best support for our controller. For that I would like to add another submodule. Should I create a clone of openocd here in the grisp project or would you rather have the submodule point directly to the official sourceforge repository: https://sourceforge.net/p/openocd/code/ci/master/tree/

**Comment by c-mauderer** [comment]
Building OpenOCD from the git repository will be a lot of trouble. It needs quite some more dependencies than the release versions. So I'll start with the release and only switch to the git HEAD if really necessary.

**Comment by c-mauderer** [comment]
i.MX6UL (and family) support has been added after the release. So we need a development version. So the question is valid again: Should we clone the openocd repo or use the SF-repo as a submodule?

**Comment by eproxus** [comment]
I would prefer to point to upstream unless we need any local modifications.

**Comment by c-mauderer** [comment]
There are no modifications necessary. I'll let it point upstream. I'll create a pull request soon.
