### ISSUE TITLE
I2C 0-based device naming

### ISSUE THREAD

**Issue by GalaxyGorilla** [grisp/grisp2-rtems-toolchain#29]
Currently in the demo i2c0 is mapped to /dev/i2c-1 which looks quite odd.

**Comment by eproxus** [comment]
In addition, the DTS contains the strings `i2c1` and `i2c2` but the code maps `i2c0` which is not present.

**Comment by eproxus** [comment]
We currently call `i2c_bus_register_imx("/dev/i2c-0", "i2c0")` and `i2c_bus_register_imx("/dev/i2c-1", "i2c1")` which *works*.

The demo calls it with different argument but doesn't actually test anything:
```
rv = i2c_bus_register_imx("/dev/i2c-1", "i2c0");
// ...

rv = i2c_bus_register_imx("/dev/i2c-2", "i2c1");
// ...
```

In the FDT only `i2c1` and `12c2` are defined. 

@c-mauderer What aliases and paths are correct here?

**Comment by GalaxyGorilla** [comment]
What does "works" here mean? Did we use `/dev/i2c-0` somewhere successfully? I can't remember that we did.

**Comment by eproxus** [comment]
https://github.com/grisp/grisp/blob/master/src/grisp_ni2c.erl#L46-L53

Works as in "tested it and it actually works" 😄

**Comment by eproxus** [comment]
I'm more concerned that we use the aliases `i2c0` and `i2c1` but "i2c0" is nowhere to be found in the FDT (does it even matter?).

**Comment by GalaxyGorilla** [comment]
You just need to follow the includes in the fdt file: https://github.com/grisp/grisp2-rtems-toolchain/blob/master/fdt/imx6ul-grisp2.dts#L7

https://github.com/grisp/grisp2-rtems-toolchain/blob/master/external/fdt/sys/gnu/dts/arm/imx6ul.dtsi#L29

**Comment by eproxus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Settle I2C bus device naming](https://trello.com/c/qO7A7aUn/55-settle-i2c-bus-device-naming)
