### ISSUE TITLE
GRiSP2 RTEMS demo in the initial image complains about EEPROM

### ISSUE THREAD

**Issue by GalaxyGorilla** [grisp/grisp2-rtems-toolchain#39]
```
Init EEPROM
ERROR: Invalid EEPROM
```

The EEPROM content is correct though!

**Comment by c-mauderer** [comment]
Is this with an up to date libgrisp build?

**Comment by GalaxyGorilla** [comment]
Very likely not. I assume you do the provisioning with the updated libgrisp version? Our Erlang code tells us that the EEPROM data is fine.

**Comment by c-mauderer** [comment]
The provisioning should be done with commit 340ef569bf04e671f109d8aab4cde0418889a31a of libgrisp which is the one with EEPROM fix. All commits after that don't do anything with the EEPROM.

**Comment by GalaxyGorilla** [comment]
@c-mauderer just for clarity: with this issue I don't want to make changes to how you do the provisioning.

The above logs are just something that cought my eye since we also have the demo on the emmc for debugging purposes. Since the user will re-flash the emmc partitions at some point for A/B updates (and therefore also the RTEMS demo) that's no problem in the long run.

**Comment by c-mauderer** [comment]
I just tried it with an up to date binary of the demo and it seems that there is no problem decoding the EEPROM:

```
GRiSP2 RTEMS Demo

Init EEPROM
sig_version: 1
serial: 1007
batch_nr: 1
prod_year: 2022
prod_month: 1
prod_day: 14
vers_major: 33
vers_minor: 2
ass_var: 1
mac_addr: 00:00:00:00:00:00
crc16: 16a6
nexus0: <RTEMS Nexus device>
```

So I assume it's only the RTEMS application delivered with the initial image. If that is (more or less) a placeholder anyway, I would suggest not to change the image. It would only mean that we add a risk that we break something else in the process.

Should we change the title of the ticket to something like "GRiSP2 RTEMS demo in the initial image complains about EEPROM" and close it with a "wontfix" tag?

**Comment by c-mauderer** [comment]
Note: Maybe "mostly up to date image" would have been the better wording. For a clean binary, we would have to do a clean re-build of the complete toolchain. I just used what I had here.

**Comment by GalaxyGorilla** [comment]
Ha thanks for testing, I was just about to do that myself.

100% agree with what you said above.

**Comment by peerst** [comment]
> So I assume it's only the RTEMS application delivered with the initial image. If that is (more or less) a placeholder anyway, I would suggest not to change the image. It would only mean that we add a risk that we break something else in the process.

Its more an extra gimmick which won't be used when we don't tell people about it
