### ISSUE TITLE
machine `arm64-apple' not recognized

### ISSUE THREAD

**Issue by d-led** [grisp/grisp2-rtems-toolchain#53]
- checked out latest commit: 6fc601909cfde31cf429524c3d6d474c19c4a24d
- `make install`
see log output
[rsb-toolchain.log.zip](https://github.com/grisp/grisp2-rtems-toolchain/files/14271707/rsb-toolchain.log.zip)

**Comment by peerst** [comment]
Thats probably the known issue I asked you for your host architecture.

Can you specify please what hardware you have Apple M1 M2 or M3 and what variant, OS etc.

**Comment by d-led** [comment]
it's an M2, 2022
Sonoma 14.3.1 (23D60)
```
g++ --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.3.0
Thread model: posix
```

**Comment by peerst** [comment]
Thanks.  I guess we need to upgrade to a more current RTEMS version (the GNU cross build tools need a newer version).  That will be a bit of work though.

**Comment by d-led** [comment]
I think I’ll close the one as it’s tracked in #52
