### ISSUE TITLE
prerequisite for make demo

### ISSUE THREAD

**Issue by dischoen** [grisp/grisp2-rtems-toolchain#6]
As requested during today's twitch meeting, I built the package with
- make install
- make demo

make demo failed with
  
`make[1]: mkimage: Command not found
make[1]: *** [Makefile:28: b-imx7/demo.zImage] Error 127
make[1]: Leaving directory '/home/dieter/projects/grisp/grisp2-rtems-toolchain/demo'
make: *** [Makefile:115: demo] Error 2
`

which I could  (on Ubuntu 18) easily fix by installing u-boot-tools.

**Comment by peerst** [comment]
Cool thanks for the quick testing!

**Comment by c-mauderer** [comment]
> which I could (on Ubuntu 18) easily fix by installing u-boot-tools.

I was originally hoping that this could be replaced by an equivalent tool from barebox. But in another thread it became obvious that barebox can't be easily build on MacOS. So most likely u-boot-tools will be a prerequisite. The pull request for integrating a CI is already collecting dependencies for the README.

**Comment by peerst** [comment]
What kind of weird image format is used here?  Apparently not raw and apparently not ELF.  Why can’t we just boot ELF?

**Comment by c-mauderer** [comment]
The format is the one that is commonly used by U-Boot with the `bootm` command. Currently a "legacy image" is used. From the man page of mkimage:

> The  old  legacy  image  format concatenates the individual parts (for example, kernel image, device tree blob and ramdisk image) and adds a 64 bytes header containing information about target architecture, operating system, image type, compression method, entry points, time stamp, checksums, etc.

That was the quickest approach: Just replace the original Linux-Image for the i.MX6 module by something compatible. I'm not sure what kind of other boot formats are supported by barebox.

**Comment by c-mauderer** [comment]
bootm supports:
- ARM Linux zImage
- U-Boot uImage
- barebox images

See: https://barebox.org/doc/latest/user/booting-linux.html

**Comment by eproxus** [comment]
This is fixed in #3 (11286f03ad9c92d57d0eb743c7e33ff8b2bbf288)
