### ISSUE TITLE
Ethernet interface in demo is not showing carrier

### ISSUE THREAD

**Issue by peerst** [grisp/grisp2-rtems-toolchain#7]
After booting the demo program like in the README here it boot successfully but plugging in a active Ethernet cable (connected to switch) the interface is still showing "no carrier"

```
SHLL [/media/mmcsd-0-0] # ifconfig
ffec0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=68000b<RXCSUM,TXCSUM,VLAN_MTU,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        ether 50:2d:f4:14:26:0b
        inet6 fe80::522d:f4ff:fe14:260b%ffec0 prefixlen 64 scopeid 0x1
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet autoselect (none)
        status: no carrier
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet 127.0.0.1 netmask 0xffffff00
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: lo
```

**Comment by c-mauderer** [comment]
That's odd. I'm sure that it already worked in the past. I'll have a look.

Did you try a hotplug or was Ethernet connected from the start?

**Comment by peerst** [comment]
Hotplug, I’ll try the latter

**Comment by eproxus** [comment]
I can get an IP from the bare box shell (without an SD card) using Internet sharing on my iMac. However, I can't figure out how to acquire an IP from the RTEMS shell (with and without Ethernet connected at boot).

**Comment by c-mauderer** [comment]
There is a dhcp daemon running in the demo application. So if the link is detected correctly it should just spring into action and get an IP. But according to the output of peerst it seems that the link isn't detected yet:

> ffec0: [...]
> status: no carrier

**Comment by eproxus** [comment]
This is the boot message for me:
```
...
mmcsd1rpmb: 524kB partition 3 at mmcsd1
usbus0: 480Mbps High Speed USB v2.0
[zone: unpcb] kern.ipc.maxsockets limit reached
info: lo0: link state changed to UP
ugen0.1: <Freescale EHCI root HUB> at usbus0
uhub0: <Freescale EHCI root HUB, class 9/0, rev 2.00/1.00, addr 1> on usbus0
waiting for SD...

SD: OK
uhub0: 1 port with 1 removable, self powered
info: ffec0: link state changed to DOWN
warning: no interfaces have a carrier
ERROR: wpa configuration does not exist: /media/mmcsd-0-0/wpa_supplicant.conf

RTEMS Shell on /dev/console. Use 'help' to list commands.
SHLL [/] #
```
And output of `ifconfig`:
```
SHLL [/] # ifconfig
ffec0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=68000b<RXCSUM,TXCSUM,VLAN_MTU,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        ether 50:2d:f4:14:26:0d
        inet6 fe80::522d:f4ff:fe14:260d%ffec0 prefixlen 64 scopeid 0x1
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet autoselect (none)
        status: no carrier
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet 127.0.0.1 netmask 0xffffff00
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: lo
```

**Comment by c-mauderer** [comment]
There is no carrier too. I'll take a look at that. I'm only stuck with other topics on that BSP (like SPI and the USB driver performance). Is Ethernet currently a blocking point for you?

**Comment by eproxus** [comment]
Not yet, since we're still working on getting Erlang to boot. But once Erlang is up networking is the next topic, and we plan to attack Ethernet first and wireless second.

**Comment by c-mauderer** [comment]
OK. I'll try to give it a higher priority on my queue. I'll just have to be a bit careful because some of the other topics are blocking points for hardware tests that have to be done before the next hardware version. USB is one of them. I need a good USB performance so that I can test the WLAN antenna.

**Comment by c-mauderer** [comment]
Somehow I lost the PHY driver during some rebase. I pushed an update to a branch of libgrisp:

    https://github.com/grisp/libgrisp/tree/cm/GRiSP2-PHY

With that Ethernet should work. My grisp2-rtems-toolchain repo is currently in a bit of a work in progress state for the USB problems. Maybe one of you could try to pull in the commit from libgrisp and check whether it solves the Ethernet problem on the current master?
