### ISSUE TITLE
LEDs not blinking in the demo

### ISSUE THREAD

**Issue by peerst** [grisp/grisp2-rtems-toolchain#8]
After successfully booting the demo (we see the RTEMS shell) we would expect the LEDs to be blinking (following the code in demo).

```
static void
led_task(rtems_task_argument arg)
{
	bool state = false;

	(void)arg;

	while(true) {
		state = !state;
		grisp_led_set1(!state, !state, state);
		grisp_led_set2(state, state, !state);
		rtems_task_wake_after(RTEMS_MILLISECONDS_TO_TICKS(250));
	}
}

```

Alas only one red led stays on like set in the bootloader

**Comment by c-mauderer** [comment]
LED isn't implemented yet. The functions are currently empty. That's open work. I'll track it in this ticket.
